version: "2"
linters:
  enable:
    - errname
  exclusions:
    generated: lax
    presets:
      - std-error-handling
  settings:
    govet:
      disable:
        - inline
formatters:
  exclusions:
    generated: lax
